# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
      
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install libsodium
      run: |
        sudo apt update
        sudo apt install -y libsodium-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Server Binary
      uses: actions/upload-release-asset@v1
      if: github.ref_type == 'tag'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/server
        asset_name: server_binary-${{ github.ref_name }}.tar.gz
        asset_content_type: application/octet-stream
        
    - name: Upload Client Binary
      uses: actions/upload-release-asset@v1
      if: github.ref_type == 'tag'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/client_fs
        asset_name: client_binary-${{ github.ref_name }}.tar.gz
        asset_content_type: application/octet-stream
